### PR TITLE
Add defined() function for define

### PR DESCRIPTION
**Pull request by da411d**
Sory, i cant explain in English, i hope you understand😅

### CODE REVIEW

**Comment by lucasexe** [comment]
Thanks for contributing to this project. I'm also a fan :)

My suggestion:
I think that you can reuse the code to avoid repeating the same code:

just changing two lines:

`if ( is_string($name) && ($name=='define') )` 
to:
`if ( is_string($name) && ($name=='define' || $name=='defined') )`

and:
```if (count($node->args)!=2)```
to: 
```if (($name=='define' && count($node->args)!=2) || ($name=='defined' && count($node->args)!=1))```

**Comment by lucasexe** [comment]
I've forgotten about the exception message. Now, I don't know if is valid reuse the code

**Comment by pk-fr** [comment]
fixed in 2.0.11
thanx for reporting the bug

**Comment by da411d** [comment]
@pk-fr you also may take a look for https://github.com/javascript-obfuscator/javascript-obfuscator
It has many interesting things, for example deobfuscate-protection.

**Pull request closed without merging**
